### ISSUE TITLE
Nan when using add cmd

### ISSUE THREAD

**Issue by Katrixerse** [bdistin/OhGodMusicBot#21]
Only in the add cmd i get a Nan then Added song to queue

Can see in the picture dont ask about the bots name its just Klaus bot but the owner of this discord changed the bots nickname
https://vgy.me/XLEflY.jpg

**Comment by ghost** [comment]
You might have another command that is interfering with the addsong command.

**Comment by Katrixerse** [comment]
Yeah forgot i had a math command which would cause it as a youtube link is not a number
