### ISSUE TITLE
i have literally no clue what's wrong

### ISSUE THREAD

**Issue by TigerFXX** [bdistin/OhGodMusicBot#22]
I do npm install and this pops up (https://gyazo.com/eaf9f2fb13c0d1002d65ac5e0b060e5e)

After that I head into my folder and do npm start and it gives me this message (https://gyazo.com/7692e4c1d4a925000d775d69747b7b2a)

Since I'm a doof and I don't know what that means, I then close it because it means nothing to me. I then get this error message (Attatched file)

Please send help, and be patient this is my first time doing a musicbot
[npm-debug copy.txt](https://github.com/bdistin/OhGodMusicBot/files/1131492/npm-debug.copy.txt)

**Comment by bdistin** [comment]
`Error: Incorrect login details were provided.`

>For obtaining a Discord Bot token, please see [this page.](https://discordapp.com/developers/docs/intro)

**Comment by YorkAARGH** [comment]
The WARN in the first screenshot are warnings, those are optional dependencies, you can safely ignore those.

The error in the second screenshot is because you haven't supplied it with a login token, you can create a bot and a token by following this guide https://anidiots.guide/getting-started/the-long-version.html

**Comment by TigerFXX** [comment]
***WILL CHANGE TOKENS AFTER FIXED***
You guys are fake news. 
As you can see by my two handy gyazos, the token in the .json (https://gyazo.com/81546095906c20721a3005928c35b7bf) is exactly the same as the one that is on my bot page.  (
![image](https://user-images.githubusercontent.com/29983059/27965960-85e2ba26-630b-11e7-9ac5-6f9566301c40.png)

**Comment by YorkAARGH** [comment]
The error does not lie, if it says incorrect login details have been supplied, then your login details are incorrect.

**Comment by TigerFXX** [comment]
Could my adminID be wrong? Would I grab the bot's or my own discord account's?

**Comment by YorkAARGH** [comment]
No, your token is wrong, the error is telling you the exact problem, not
your admin ids, or owner ids, it's your token.

**Comment by bdistin** [comment]
![fakeNews](https://puu.sh/wDVBD/73f3937cd6.png)

You're right, clearly they are the same, you know, except for the whole last part...

**Comment by TigerFXX** [comment]
Found my boo boo, the .json won't save in my editor. It's Atom.

**Comment by TigerFXX** [comment]
And every time I refresh the bot page a new token appears, that's where the problem lies.

**Comment by eslachance** [comment]
That's not a problem. Tokens have a timestamp-based component to it, every token generated even after refreshing is perfectly valid. They all get invalidated if you reset the token.

**Comment by TigerFXX** [comment]
Now the bot is up and running. When I do the ++play, it says I don't have FFMPEG installed, in which I do. Here is the exact text I put in my Path system variables


C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;c:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;c:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;c:\Program Files (x86)\Common Files\Roxio Shared\12.0\DLLShared\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;c:\ffmpeg\bin

Is there anything wrong here?

**Comment by eslachance** [comment]
`npm install ffmpeg-binaries` within the bot folder. problem solved.

**Comment by TigerFXX** [comment]
Now it can't find an opus engine

**Comment by gavwin** [comment]
npm install node-opus

**Comment by TigerFXX** [comment]
[npm-debug copy.txt](https://github.com/bdistin/OhGodMusicBot/files/1131821/npm-debug.copy.txt)

**Comment by eslachance** [comment]
Alright for further support please join the Discord.js guild on https://discord.gg/bRCvFy9
