### ISSUE TITLE
Vote To Skip?

### ISSUE THREAD

**Issue by fernnp** [bdistin/OhGodMusicBot#24]
Is there anyway I can edit the !skip command so that depending on how many people are in the voice channel with the bot they all have to !skip inorder for the song to skip?

**Comment by bdistin** [comment]
This is example code (likely outdated example code, but examples none the less). You are free to do whatever you want with your copy of the code, or code inspired by this code.

**Comment by fernnp** [comment]
Would you be able to give me the code so I can create a vote to skip method?

**Comment by bdistin** [comment]
The repo is open source? And no I will not be writing anything for you...
