### ISSUE TITLE
Bot doesn't play songs

### ISSUE THREAD

**Issue by ghost** [bdistin/OhGodMusicBot#37]
I used the song Bloom by Troye Sivan for example, don't question it!

Console log:

`(node:33536) DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead
{ '444472391087816708': { playing: true, songs: [ [Object] ] } }
{ url: 'https://www.youtube.com/watch?v=rxmtHVSVjdo',
  title: 'Troye Sivan - Bloom (Lyric Video)',
  requester: 'Samcool236 🇦🇺' }
undefined
{ '444472391087816708': { playing: true, songs: [] } }
undefined
{ '444472391087816708': { playing: true, songs: [ [Object], [Object], [Object] ] } }
{ url: 'https://www.youtube.com/watch?v=rxmtHVSVjdo',
  title: 'Troye Sivan - Bloom (Lyric Video)',
  requester: 'Samcool236 🇦🇺' }
{ url: 'https://www.youtube.com/watch?v=rxmtHVSVjdo',
  title: 'Troye Sivan - Bloom (Lyric Video)',
  requester: 'Samcool236 🇦🇺' }
{ url: 'https://www.youtube.com/watch?v=rxmtHVSVjdo',
  title: 'Troye Sivan - Bloom (Lyric Video)',
  requester: 'Samcool236 🇦🇺' }
undefined`

I added the same song 3 times in the queue, the bot joins the voice channel, fine. However, it doesn't play the songs, it just auto skips all of the songs till the queue is empty.

Edit: I tried making another music bot from scratch using another node module, and it does the same thing. Is the issue on my end?

**Comment by Paultje52** [comment]
Are you hosting on a pi?

**Comment by ghost** [comment]
I am just hosting the bot from Visual Studio Code, for temporary use so I can play around with the code and experiment

**Comment by Paultje52** [comment]
install discord.js with opusscript: 
```
npm i -s discord.js opusscript
```

And don't fergot to install ffmpeg, you can se how in the readmy.md

**Comment by ghost** [comment]
Turns out my $PATH variable for FFmpeg set itself incorrectly. I found it's path, and manually set it.
