### ISSUE TITLE
First song in queue playing twice

### ISSUE THREAD

**Issue by Darqam** [bdistin/OhGodMusicBot#8]
Heya,

So I'm not quite sure why but it seems that the first song I put in the queue will always play twice, even if the queue indicates it is present only once. Is there a setting I'm not toggling somewhere or is this actually an issue.

Unrelated, I'm also surprised there isn't a leave command. Could you not include something along the lines of: `'leave': (msg) => {	msg.guild.member(client.user).voiceChannel.leave();	},`? It seems to work fine and still keeps the code under 100 lines if that's important.

**Comment by Serious-Cate** [comment]
this code is only example for almost perfect music bot for starters with music.

As the bug it sounds interesting :thinking:

**Comment by Darqam** [comment]
In case it's relevant:
* discord.js: V 11.0.0
* node: 6.10.0

**Comment by rbJARB** [comment]
I'm getting the same issue, I think It's because the song is being played and not removed from the queue initially, therefore its still in the queue although its already playing.

**Comment by bdistin** [comment]
bug fixed in latest commit. Wasn't shifting away the first song

**Comment by Darqam** [comment]
<3 thanks for the fix.
